---
name: Validate HACS

on:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    steps:
      - name: HACS Action
        uses: hacs/action@22.5.0
        with:
          category: integration
